### ISSUE TITLE
Paper interesantes para revisar

### ISSUE THREAD

**Issue by Lia001218** [geeksLabTech/epidemic-classification-ml-project#1]

**Comment by Lia001218** [comment]
https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=9258765
Analysis model of the most important factors in
Covid-19 through data mining, descriptive statistics
and random forest
Esta gente usan un algoritmo de ML para identificar en un dataset las variables que son mas importantes y obtener un dataset mas limpio y con menor cantidad de ruindo

**Comment by Lia001218** [comment]
https://link.springer.com/content/pdf/10.1007/978-3-030-35139-7_7.pdf
Artificial Intelligence Applications in Tracking Health Behaviors During Disease Epidemics
Util si el objetivo es predecir cual es el conjunto de medidas dada una nfermedad determinada

**Comment by Lia001218** [comment]
https://arxiv.org/pdf/2002.07112.pdf
Artificial Intelligence Forecasting of Covid-19 in China
Util dependiendo del objetivo, predicen la dinamica de contagio del covid

**Comment by DanielUH2019** [comment]
COVID-19 Future Forecasting Using Supervised
Machine Learning Models
https://ieeexplore.ieee.org/ielx7/6287639/8948470/09099302.pdf

**Comment by DanielUH2019** [comment]
A profcient approach to forecast COVID‑19 spread via optimized dynamic machine learning models
https://www.nature.com/articles/s41598-022-06218-3.pdf

**Comment by DanielUH2019** [comment]
Supervised Machine Learning Models for Prediction of COVID‑19 Infection using Epidemiology Dataset
https://link.springer.com/content/pdf/10.1007/s42979-020-00394-7.pdf

**Comment by DanielUH2019** [comment]
Modified SEIR and AI prediction of the epidemics trend of COVID-19 in China under public health interventions
https://pdfs.semanticscholar.org/669b/51fc197043d3673336b2d3a95443a4471876.pdf?_gl=1*12kkfo2*_ga*MTE4MTAwMDI4Mi4xNjc4MTY4NDMy*_ga_H7P4ZT52H5*MTY3ODM5ODk4MC43LjEuMTY3ODQwMDM2OS4wLjAuMA..

**Comment by DanielUH2019** [comment]
AI-Driven Tools for Coronavirus Outbreak: Need of Active Learning and Cross-Population Train/Test Models on Multitudinal/Multimodal Data
https://link.springer.com/content/pdf/10.1007/s10916-020-01562-1.pdf

**Comment by maux96** [comment]
A Deep Learning Framework for COVID Outbreak
Prediction
https://arxiv.org/pdf/2010.00382.pdf

**Comment by maux96** [comment]
Infectious disease outbreak prediction using media articles with machine learning models
https://www.nature.com/articles/s41598-021-83926-2

**Comment by DanielUH2019** [comment]
Eir: A Python Package for Epidemic Simulation
https://pdfs.semanticscholar.org/1511/4c1b95e7a77a078cf2a824f0aed2455c5f28.pdf?_gl=1*13ynyfy*_ga*MTE4MTAwMDI4Mi4xNjc4MTY4NDMy*_ga_H7P4ZT52H5*MTY3ODQxMzcyMy4xMC4xLjE2Nzg0MTYxNDkuMC4wLjA.

**Comment by DanielUH2019** [comment]
nosoi: A stochastic agent‐based transmission chain simulation framework in r
https://besjournals.onlinelibrary.wiley.com/doi/pdfdirect/10.1111/2041-210X.13422

**Comment by DanielUH2019** [comment]
Hospital preparedness during epidemics using simulation:
the case of COVID-19
https://link.springer.com/content/pdf/10.1007/s10100-021-00779-w.pdf

**Comment by DanielUH2019** [comment]
A Simulation Study of Coronavirus as an Epidemic Disease Using Agent-Based Modeling.
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7883357/

**Comment by DanielUH2019** [comment]
June: open-source individual-based epidemiology simulation
https://discovery.ucl.ac.uk/id/eprint/10132387/1/rsos.210506.pdf

**Comment by DanielUH2019** [comment]
Likelihood-Based Inference for Partially Observed Epidemics on Dynamic Networks
https://arxiv.org/pdf/1910.04221.pdf

**Comment by DanielUH2019** [comment]
A new virus-centric epidemic modeling approach, 1: General theory and machine learning simulation of 2020 SARS Cov 2 (COVID-19) for Belgium, France, Italy, and Spain
https://msp.org/memocs/2020/8-3/memocs-v8-n3-p02-s.pdf

**Comment by DanielUH2019** [comment]
COVID-19 Spread in Saudi Arabia: Modeling, Simulation and Analysis
https://pdfs.semanticscholar.org/7002/df048d3f1586d6c6d07b3f345c90982e3b56.pdf?_gl=1*15xs124*_ga*MTE4MTAwMDI4Mi4xNjc4MTY4NDMy*_ga_H7P4ZT52H5*MTY3ODQyMDc3NC4xMS4xLjE2Nzg0MjU5MDUuMC4wLjA.

**Comment by DianeCM** [comment]
COVID-19 Pandemic Prediction for Hungary; A Hybrid Machine Learning Approach
https://www.mdpi.com/2227-7390/8/6/890#B58-mathematics-08-00890

**Comment by DianeCM** [comment]
Supervised Learning Models for the Preliminary Detection of COVID-19 in Patients Using Demographic and Epidemiological Parameters
https://www.mdpi.com/2078-2489/13/7/330

**Comment by SergiPantoja** [comment]
Algunas cosas interesantes

- https://www.researchgate.net/profile/Rajeshwar-Singh-3/publication/332819639_Sentiment_analysis_using_machine_learning_techniques_to_predict_outbreaks_and_epidemics/links/5ccb31d34585153c8c681aad/Sentiment-analysis-using-machine-learning-techniques-to-predict-outbreaks-and-epidemics.pdf 
analisis de sentimiento en redes sociales para predecir outbreaks de epidemias, especialmente Twitter. Aqui mas bien hacen una compilacion de distintos papers que hacen este tipo de analisis y que tecnicas de ML utilizan.
- Comparative analysis of machine learning-based classification models using sentiment classification of tweets related to COVID-19 pandemic
https://www.sciencedirect.com/science/article/pii/S2214785321032843
- COVID-19 outbreak: An ensemble pre-trained deep learning model for detecting informative tweets
https://www.sciencedirect.com/science/article/pii/S156849462100418X
- Deep learning approaches for COVID-19 detection based on chest X-ray images
https://www.sciencedirect.com/science/article/pii/S0957417420308198
- A review of deep learning-based detection methods for COVID-19
https://www.sciencedirect.com/science/article/pii/S0010482522000257

**Comment by JavierOramas** [comment]
https://www.sciencedirect.com/science/article/pii/S1755436515000511?via%3Dihub

hacen modelacion de epidemia de influenza utilizando grupos de edades y usan unas formulas de probabilidad para sacar los contactos

**Comment by JavierOramas** [comment]
https://ieeexplore.ieee.org/abstract/document/7558120

We propose an epidemic-model-based tensor deconvolution framework in which the spatiotemporal patterns of social contact are represented by the factors of the tensors.

https://sci-hub.se/10.1109/tpami.2016.2605095
